#include<stdio.h>
void main()
{
char c;
scanf("%c",&c);

switch(c)
{
case '0': printf("%d",c);
break;
case '1': printf("%d",c);
break;
case '2': printf("%d",c);
break;
case '3': printf("%d",c);
break;
case '4': printf("%d",c);
break;
case '5': printf("%d",c);
break;
case '6': printf("%d",c);
break;
case '7': printf("%d",c);
break;
case '8': printf("%d",c);
break;
case '9': printf("%d",c);
break;
case 'a': printf("%d",c);
break;
case 'b': printf("%d",c);
break;
case 'c': printf("%d",c);
break;
case 'd': printf("%d",c);
break;
case 'e': printf("%d",c);
break;
case 'f': printf("%d",c);
break;
case 'g': printf("%d",c);
break;
case 'h': printf("%d",c);
break;
case 'i': printf("%d",c);
break;
case 'j': printf("%d",c);
break;
case 'k': printf("%d",c);
break;
case 'l': printf("%d",c);
break;
case 'm': printf("%d",c);
break;
case 'n': printf("%d",c);
break;
case 'o': printf("%d",c);
break;
case 'p': printf("%d",c);
break;
case 'q': printf("%d",c);
break;
case 'r': printf("%d",c);
break;
case 's': printf("%d",c);
break;
case 't': printf("%d",c);
break;
case 'u': printf("%d",c);
break;
case 'v': printf("%d",c);
break;
case 'w': printf("%d",c);
break;
case 'x': printf("%d",c);
break;
case 'y': printf("%d",c);
break;
case 'z': printf("%d",c);
break;
case 'A': printf("%d",c);
break;
case 'B': printf("%d",c);
break;
case 'C': printf("%d",c);
break;
case 'D': printf("%d",c);
break;
case 'E': printf("%d",c);
break;
case 'F': printf("%d",c);
break;
case 'G': printf("%d",c);
break;
case 'H': printf("%d",c);
break;
case 'I': printf("%d",c);
break;
case 'J': printf("%d",c);
break;
case 'K': printf("%d",c);
break;
case 'L': printf("%d",c);
break;
case 'M': printf("%d",c);
break;
case 'N': printf("%d",c);
break;
case 'O': printf("%d",c);
break;
case 'P': printf("%d",c);
break;
case 'Q': printf("%d",c);
break;
case 'R': printf("%d",c);
break;
case 'S': printf("%d",c);
break;
case 'T': printf("%d",c);
break;
case 'U': printf("%d",c);
break;
case 'V': printf("%d",c);
break;
case 'W': printf("%d",c);
break;
case 'X': printf("%d",c);
break;
case 'Y': printf("%d",c);
break;
case 'Z': printf("%d",c);
break;
default:break;
}
}
